FROM {{ item.image }}

RUN if [ -f /etc/debian_version ]; then \
    apt-get update && \
    apt-get install -y python3 systemd sudo && \
    apt-get clean; \
    elif [ -f /etc/redhat-release ]; then \
    dnf install -y python3.11 systemd sudo && \
    dnf clean all; \
    alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1; \
    fi

ENV container=docker
ENV HOME=/root

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]